### PR TITLE
Added collectionView:didMoveItemAtIndexPath:toIndexPath:

### PR DESCRIPTION
**Pull request by ndlupine**
Hi Luke!

We found it helpful on our project to have a completion handler so we can update cells affected by the drag-and-drop operation. Thought it might be useful for others as well. Thanks a lot for open sourcing this project, it was really handy and easy to use!

-n

### CODE REVIEW

**Comment by jbweimar** [comment]
thanks ndlupine.
this code needs to be merged. i needed it to make my collectionview work. thanks!

**Comment by lukescott** [comment]
Hi ndlupine,

I'm sorry for taking so long. Life has been getting in the way lately.

Can you please squash your commits so I can merge this? Thanks!

**Comment by ndlupine** [comment]
Hi Luke! Sorry, I'm a little inexperienced dealing with merge requests. I had a difficult time getting my changes into a single commit after our project incorporated the changes. At any rate, I don't have write access to our fork of the repo anymore, so I'm not sure if there's anything I can do, unless I make a fork of my own and reimplement the change. Is there a way you can squash it in merging on your end, or just merge in the two commits? Sorry for the mess!

Nick

**Comment by lukescott** [comment]
Hi Nick,

I just merged the changes, although it's now disconnected from the fork. You did get credit for it (click contributors), but the contributors count is wrong.

There are a couple ways to squash commits. `git rebase -i ..` is a good way, although it's easier when you have a feature branch so you can `git rebase -i origin/master`. Another way is to `git reset --soft [hash]` to undo the commits and then `git commit -m "New message"`. The soft reset will keep the changes in the working tree.

**Pull request closed without merging**
